# --- DATABASE WITH 220+ US COLLEGES ---
# Format: (Name, SAT, AcceptRate, Friendly, Specialties, SchoolNames, State, Fees)
# SAT = Middle 50% median (approximate midpoint of 25th-75th percentile range)
# AcceptRate = Overall acceptance rate as decimal (0.04 = 4%)
#   Based on most recent Common Data Set / NCES IPEDS data
# Friendly = Indian international student friendliness: "High", "Med", "Low"
#   "High" = Large Indian community, actively recruits internationals, good support
#   "Med"  = Moderate Indian presence, standard international process
#   "Low"  = State school bias toward in-state, few intl spots, limited Indian community
# Specialties = List of strong program tags
# SchoolNames = Dict mapping specialty tags to specific school/college names
# State = US state abbreviation
# Fees = Total estimated Cost of Attendance for international students
#
# Data sourced from: Common Data Sets, US News, NCES/IPEDS,
# Open Doors/SEVIS reports, College Scorecard, official university websites.

COLLEGES = [
    ('Harvard University', 1550, 0.034, 'Med', ['Econ', 'Bio', 'CS', 'Sci'],
     {'Econ': 'Economics', 'Bio': 'Medical School', 'CS': 'SEAS', 'Sci': 'FAS'}, 'MA', 82000),
    ('Stanford University', 1550, 0.037, 'Med', ['CS', 'Eng', 'Econ', 'Sci'],
     {'CS': 'Engineering', 'Eng': 'Engineering', 'Econ': 'Economics', 'Sci': 'H&S'}, 'CA', 87000),
    ('MIT', 1555, 0.039, 'High', ['CS', 'Eng', 'Sci', 'Econ'],
     {'CS': 'EECS', 'Eng': 'Engineering', 'Sci': 'Science', 'Econ': 'Sloan'}, 'MA', 82000),
    ('Princeton University', 1540, 0.037, 'Med', ['Econ', 'Sci', 'CS', 'Eng'],
     {'Econ': 'Economics', 'Sci': 'Natural Sciences', 'CS': 'CS', 'Eng': 'Engineering'}, 'NJ', 80000),
    ('Yale University', 1540, 0.046, 'Med', ['Econ', 'Sci', 'Bio'],
     {'Econ': 'Economics', 'Sci': 'FAS', 'Bio': 'Medicine'}, 'CT', 84000),
    ('Caltech', 1560, 0.032, 'High', ['Sci', 'Eng', 'CS'],
     {'Sci': 'PMA', 'Eng': 'Engineering', 'CS': 'Computing'}, 'CA', 83000),
    ('Columbia University', 1540, 0.039, 'High', ['Econ', 'CS', 'Eng', 'Biz'],
     {'Econ': 'Economics', 'CS': 'CS', 'Eng': 'SEAS', 'Biz': 'Columbia Business'}, 'NY', 86000),
    ('UPenn', 1530, 0.054, 'Med', ['Biz', 'Econ', 'Eng', 'Bio'],
     {'Biz': 'Wharton', 'Econ': 'Wharton', 'Eng': 'SEAS', 'Bio': 'Perelman'}, 'PA', 84000),
    ('University of Chicago', 1540, 0.052, 'Med', ['Econ', 'Sci', 'Biz'],
     {'Econ': 'Economics', 'Sci': 'Physical Sciences', 'Biz': 'Booth'}, 'IL', 84000),
    ('Duke University', 1530, 0.05, 'Med', ['Bio', 'Econ', 'CS', 'Eng'],
     {'Bio': 'Medicine', 'Econ': 'Economics', 'CS': 'CS', 'Eng': 'Pratt'}, 'NC', 83000),
    ('Johns Hopkins University', 1540, 0.065, 'Med', ['Bio', 'Sci', 'Eng'],
     {'Bio': 'Medicine', 'Sci': 'Krieger', 'Eng': 'Whiting'}, 'MD', 82000),
    ('Northwestern University', 1520, 0.07, 'Med', ['Econ', 'Biz', 'Eng', 'CS'],
     {'Econ': 'Economics', 'Biz': 'Kellogg', 'Eng': 'McCormick', 'CS': 'McCormick'}, 'IL', 84000),
    ('Dartmouth College', 1510, 0.062, 'Med', ['Econ', 'CS', 'Eng'],
     {'Econ': 'Economics', 'CS': 'CS', 'Eng': 'Thayer'}, 'NH', 83000),
    ('Brown University', 1510, 0.05, 'Med', ['CS', 'Econ', 'Sci'],
     {'CS': 'CS', 'Econ': 'Economics', 'Sci': 'Sciences'}, 'RI', 83000),
    ('Vanderbilt University', 1520, 0.056, 'Med', ['Econ', 'Eng', 'Bio'],
     {'Econ': 'Economics', 'Eng': 'Engineering', 'Bio': 'Medicine'}, 'TN', 82000),
    ('Cornell University', 1510, 0.079, 'High', ['CS', 'Eng', 'Biz', 'Bio'],
     {'CS': 'Cornell Tech', 'Eng': 'Engineering', 'Biz': 'Dyson/SHA', 'Bio': 'CALS'}, 'NY', 83000),
    ('Rice University', 1530, 0.077, 'Med', ['Eng', 'Sci', 'CS'],
     {'Eng': 'Brown School', 'Sci': 'Wiess', 'CS': 'CS'}, 'TX', 72000),
    ('WashU St. Louis', 1520, 0.11, 'Med', ['Bio', 'Biz', 'Eng', 'CS'],
     {'Bio': 'Medicine', 'Biz': 'Olin', 'Eng': 'McKelvey', 'CS': 'McKelvey'}, 'MO', 82000),
    ('Carnegie Mellon University', 1540, 0.11, 'High', ['CS', 'Eng', 'Biz', 'Sci'],
     {'CS': 'SCS', 'Eng': 'Engineering', 'Biz': 'Tepper', 'Sci': 'MCS'}, 'PA', 81000),
    ('UCLA', 1460, 0.086, 'Low', ['Bio', 'Econ', 'CS', 'Eng'],
     {'Bio': 'Geffen', 'Econ': 'Economics', 'CS': 'Engineering', 'Eng': 'Samueli'}, 'CA', 68000),
    ('UC Berkeley', 1470, 0.116, 'Low', ['CS', 'Eng', 'Econ', 'Sci'],
     {'CS': 'EECS', 'Eng': 'Engineering', 'Econ': 'Economics', 'Sci': 'Chemistry'}, 'CA', 72000),
    ('Georgetown University', 1470, 0.12, 'Med', ['Biz', 'Econ'],
     {'Biz': 'McDonough', 'Econ': 'Economics'}, 'DC', 82000),
    ('Emory University', 1480, 0.11, 'Med', ['Bio', 'Biz', 'Econ'],
     {'Bio': 'Medicine', 'Biz': 'Goizueta', 'Econ': 'Economics'}, 'GA', 78000),
    ('University of Notre Dame', 1480, 0.12, 'Low', ['Biz', 'Eng'],
     {'Biz': 'Mendoza', 'Eng': 'Engineering'}, 'IN', 80000),
    ('USC', 1470, 0.099, 'High', ['Biz', 'CS', 'Eng'],
     {'Biz': 'Marshall', 'CS': 'Viterbi', 'Eng': 'Viterbi'}, 'CA', 84000),
    ('NYU', 1470, 0.08, 'High', ['Biz', 'Econ', 'CS'],
     {'Biz': 'Stern', 'Econ': 'Economics', 'CS': 'Tandon/Courant'}, 'NY', 84000),
    ('University of Michigan', 1480, 0.177, 'Med', ['Biz', 'CS', 'Eng', 'Sci'],
     {'Biz': 'Ross', 'CS': 'CSE', 'Eng': 'Engineering', 'Sci': 'LSA'}, 'MI', 72000),
    ('Tufts University', 1490, 0.095, 'Med', ['Bio', 'Eng', 'CS'],
     {'Bio': 'Medicine', 'Eng': 'Engineering', 'CS': 'CS'}, 'MA', 82000),
    ('Georgia Tech', 1480, 0.16, 'Low', ['CS', 'Eng', 'Biz'],
     {'CS': 'Computing', 'Eng': 'Engineering', 'Biz': 'Scheller'}, 'GA', 55000),
    ('University of Virginia', 1460, 0.186, 'Low', ['Biz', 'Econ', 'Eng'],
     {'Biz': 'McIntire', 'Econ': 'Economics', 'Eng': 'Engineering'}, 'VA', 72000),
    ('UNC Chapel Hill', 1440, 0.167, 'Low', ['Biz', 'Bio', 'CS'],
     {'Biz': 'Kenan-Flagler', 'Bio': 'Medicine', 'CS': 'CS'}, 'NC', 58000),
    ('Boston University', 1440, 0.11, 'High', ['Bio', 'Biz', 'Eng', 'CS'],
     {'Bio': 'Medicine', 'Biz': 'Questrom', 'Eng': 'Engineering', 'CS': 'CS'}, 'MA', 82000),
    ('Northeastern University', 1460, 0.067, 'High', ['CS', 'Eng', 'Biz'],
     {'CS': 'Khoury', 'Eng': 'Engineering', 'Biz': "D'Amore-McKim"}, 'MA', 78000),
    ('Tulane University', 1430, 0.08, 'Med', ['Biz', 'Bio'],
     {'Biz': 'Freeman', 'Bio': 'Medicine'}, 'LA', 78000),
    ('Williams College', 1520, 0.09, 'Med', ['Econ', 'Sci'],
     {'Econ': 'Economics', 'Sci': 'Sciences'}, 'MA', 78000),
    ('Amherst College', 1510, 0.07, 'Med', ['Econ', 'Sci'],
     {'Econ': 'Economics', 'Sci': 'Sciences'}, 'MA', 78000),
    ('Swarthmore College', 1510, 0.07, 'Med', ['Eng', 'CS', 'Sci'],
     {'Eng': 'Engineering', 'CS': 'CS', 'Sci': 'Sciences'}, 'PA', 78000),
    ('Pomona College', 1500, 0.07, 'Med', ['Econ', 'Sci'],
     {'Econ': 'Economics', 'Sci': 'Sciences'}, 'CA', 78000),
    ('Wellesley College', 1480, 0.13, 'Med', ['Econ', 'CS'],
     {'Econ': 'Economics', 'CS': 'CS'}, 'MA', 78000),
    ('Bowdoin College', 1480, 0.085, 'Med', ['Econ'],
     {'Econ': 'Economics'}, 'ME', 78000),
    ('Middlebury College', 1460, 0.14, 'Med', ['Econ'],
     {'Econ': 'Economics'}, 'VT', 78000),
    ('Carleton College', 1490, 0.16, 'Med', ['Sci', 'CS'],
     {'Sci': 'Sciences', 'CS': 'CS'}, 'MN', 78000),
    ('Claremont McKenna', 1470, 0.11, 'Med', ['Econ', 'Biz'],
     {'Econ': 'Economics', 'Biz': 'Robert Day'}, 'CA', 78000),
    ('Harvey Mudd College', 1540, 0.13, 'Med', ['CS', 'Eng', 'Sci'],
     {'CS': 'CS', 'Eng': 'Engineering', 'Sci': 'Sciences'}, 'CA', 82000),
    ('Haverford College', 1460, 0.15, 'Med', ['Sci'],
     {'Sci': 'Sciences'}, 'PA', 78000),
    ('Vassar College', 1450, 0.18, 'Med', ['Sci'],
     {'Sci': 'Sciences'}, 'NY', 78000),
    ('Colby College', 1440, 0.07, 'Med', ['Econ'],
     {'Econ': 'Economics'}, 'ME', 76000),
    ('Hamilton College', 1450, 0.12, 'Med', ['Econ'],
     {'Econ': 'Economics'}, 'NY', 76000),
    ('Grinnell College', 1430, 0.09, 'High', ['Sci', 'CS'],
     {'Sci': 'Sciences', 'CS': 'CS'}, 'IA', 72000),
    ('Boston College', 1460, 0.16, 'Med', ['Biz', 'Econ'],
     {'Biz': 'Carroll', 'Econ': 'Economics'}, 'MA', 82000),
    ('Babson College', 1370, 0.22, 'High', ['Biz'],
     {'Biz': 'Entrepreneurship'}, 'MA', 74000),
    ('University of Rochester', 1420, 0.39, 'High', ['Econ', 'Sci', 'Eng', 'Bio'],
     {'Econ': 'Economics', 'Sci': 'Hajim', 'Eng': 'Hajim', 'Bio': 'Medicine'}, 'NY', 76000),
    ('Case Western Reserve', 1440, 0.29, 'High', ['Bio', 'Eng', 'Sci', 'CS'],
     {'Bio': 'Medicine', 'Eng': 'Engineering', 'Sci': 'A&S', 'CS': 'Engineering'}, 'OH', 72000),
    ('William & Mary', 1430, 0.33, 'Low', ['Econ', 'Biz'],
     {'Econ': 'Economics', 'Biz': 'Mason'}, 'VA', 62000),
    ('UC San Diego', 1410, 0.24, 'Low', ['Bio', 'CS', 'Eng', 'Sci'],
     {'Bio': 'Medicine', 'CS': 'CSE', 'Eng': 'Jacobs', 'Sci': 'Physical Sciences'}, 'CA', 68000),
    ('Brandeis University', 1420, 0.32, 'High', ['Econ', 'Sci', 'Biz'],
     {'Econ': 'Economics', 'Sci': 'Sciences', 'Biz': 'IBS'}, 'MA', 78000),
    ('Olin College', 1510, 0.16, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'Engineering'}, 'MA', 76000),
    ('Cooper Union', 1480, 0.13, 'High', ['Eng'],
     {'Eng': 'Nerken'}, 'NY', 60000),
    ('UC Santa Barbara', 1380, 0.25, 'Low', ['Sci', 'CS', 'Eng'],
     {'Sci': 'Letters & Science', 'CS': 'CS', 'Eng': 'Engineering'}, 'CA', 68000),
    ('UC Irvine', 1370, 0.21, 'Low', ['CS', 'Bio', 'Eng'],
     {'CS': 'Donald Bren ICS', 'Bio': 'Medicine', 'Eng': 'Samueli'}, 'CA', 66000),
    ('University of Florida', 1400, 0.23, 'Low', ['Bio', 'Eng', 'Biz'],
     {'Bio': 'Medicine', 'Eng': 'Herbert Wertheim', 'Biz': 'Warrington'}, 'FL', 49000),
    ('Wake Forest', 1390, 0.2, 'Med', ['Biz', 'Bio'],
     {'Biz': 'School of Business', 'Bio': 'Medicine'}, 'NC', 78000),
    ('Villanova University', 1400, 0.23, 'Med', ['Biz', 'Eng'],
     {'Biz': 'VSB', 'Eng': 'Engineering'}, 'PA', 74000),
    ('UT Austin', 1400, 0.29, 'Low', ['CS', 'Eng', 'Biz', 'Sci'],
     {'CS': 'UTCS', 'Eng': 'Cockrell', 'Biz': 'McCombs', 'Sci': 'CNS'}, 'TX', 58000),
    ('UIUC', 1430, 0.44, 'High', ['CS', 'Eng', 'Sci', 'Biz'],
     {'CS': 'Grainger CS', 'Eng': 'Grainger', 'Sci': 'LAS', 'Biz': 'Gies'}, 'IL', 54000),
    ('UW Madison', 1420, 0.49, 'Med', ['Eng', 'Sci', 'CS', 'Biz'],
     {'Eng': 'Engineering', 'Sci': 'L&S', 'CS': 'CS', 'Biz': 'Wisconsin School of Business'}, 'WI', 56000),
    ('UMD College Park', 1420, 0.44, 'Med', ['CS', 'Eng', 'Sci', 'Biz'],
     {'CS': 'CS', 'Eng': 'Clark', 'Sci': 'CMNS', 'Biz': 'Smith'}, 'MD', 56000),
    ('UW Seattle', 1400, 0.46, 'Med', ['CS', 'Eng', 'Bio'],
     {'CS': 'Paul Allen', 'Eng': 'Engineering', 'Bio': 'Medicine'}, 'WA', 58000),
    ('Lehigh University', 1380, 0.37, 'Med', ['Eng', 'Biz', 'CS'],
     {'Eng': 'Rossin', 'Biz': 'Business', 'CS': 'CS'}, 'PA', 74000),
    ('Bentley University', 1320, 0.41, 'High', ['Biz'],
     {'Biz': 'Business'}, 'MA', 72000),
    ('Cal Poly SLO', 1360, 0.3, 'Low', ['CS', 'Eng'],
     {'CS': 'CS', 'Eng': 'Engineering'}, 'CA', 46000),
    ('Pepperdine University', 1340, 0.34, 'Med', ['Biz'],
     {'Biz': 'Seaver'}, 'CA', 78000),
    ('Rose-Hulman', 1390, 0.68, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS & SE'}, 'IN', 68000),
    ('Colgate University', 1430, 0.12, 'Med', ['Econ'],
     {'Econ': 'Economics'}, 'NY', 76000),
    ('Purdue University', 1350, 0.53, 'High', ['CS', 'Eng', 'Sci'],
     {'CS': 'CS', 'Eng': 'Engineering', 'Sci': 'Science'}, 'IN', 46000),
    ('Ohio State University', 1370, 0.53, 'Med', ['Biz', 'Eng', 'CS'],
     {'Biz': 'Fisher', 'Eng': 'Engineering', 'CS': 'CSE'}, 'OH', 56000),
    ('University of Georgia', 1340, 0.43, 'Low', ['Biz'],
     {'Biz': 'Terry'}, 'GA', 50000),
    ('Santa Clara University', 1390, 0.49, 'High', ['Biz', 'Eng', 'CS'],
     {'Biz': 'Leavey', 'Eng': 'Engineering', 'CS': 'CS'}, 'CA', 76000),
    ('RPI', 1400, 0.57, 'High', ['Eng', 'CS', 'Sci'],
     {'Eng': 'Engineering', 'CS': 'CS', 'Sci': 'Science'}, 'NY', 76000),
    ('Virginia Tech', 1340, 0.57, 'Med', ['CS', 'Eng'],
     {'CS': 'CS', 'Eng': 'Engineering'}, 'VA', 56000),
    ('Texas A&M', 1290, 0.57, 'Low', ['Eng', 'Biz'],
     {'Eng': 'Engineering', 'Biz': 'Mays'}, 'TX', 52000),
    ('University of Connecticut', 1330, 0.56, 'Med', ['Biz', 'Eng'],
     {'Biz': 'School of Business', 'Eng': 'Engineering'}, 'CT', 58000),
    ('University of Pittsburgh', 1350, 0.42, 'Med', ['Bio', 'Eng', 'CS'],
     {'Bio': 'Medicine', 'Eng': 'Swanson', 'CS': 'SCI'}, 'PA', 52000),
    ('WPI', 1380, 0.58, 'High', ['Eng', 'CS', 'Sci'],
     {'Eng': 'Engineering', 'CS': 'CS', 'Sci': 'Sciences'}, 'MA', 72000),
    ('NC State', 1360, 0.47, 'Med', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'NC', 50000),
    ('UC Davis', 1320, 0.37, 'Low', ['Bio', 'Sci', 'Eng'],
     {'Bio': 'Medicine', 'Sci': 'L&S', 'Eng': 'Engineering'}, 'CA', 66000),
    ('Bates College', 1410, 0.14, 'Med', ['Econ'],
     {'Econ': 'Economics'}, 'ME', 76000),
    ('Oberlin College', 1400, 0.33, 'High', ['Sci'],
     {'Sci': 'Sciences'}, 'OH', 74000),
    ('Rutgers University', 1350, 0.66, 'High', ['Biz', 'CS', 'Eng'],
     {'Biz': 'RBS', 'CS': 'CS', 'Eng': 'Engineering'}, 'NJ', 52000),
    ('Penn State', 1310, 0.55, 'Med', ['Biz', 'Eng', 'CS'],
     {'Biz': 'Smeal', 'Eng': 'Engineering', 'CS': 'IST'}, 'PA', 56000),
    ('UMass Amherst', 1340, 0.64, 'High', ['CS', 'Eng'],
     {'CS': 'Manning CICS', 'Eng': 'Engineering'}, 'MA', 56000),
    ('CU Boulder', 1290, 0.8, 'Med', ['Sci', 'Eng', 'CS'],
     {'Sci': 'A&S', 'Eng': 'Engineering', 'CS': 'CS'}, 'CO', 56000),
    ('University of Minnesota', 1350, 0.73, 'Med', ['Eng', 'Biz', 'CS'],
     {'Eng': 'CSE', 'Biz': 'Carlson', 'CS': 'CS'}, 'MN', 52000),
    ('Scripps College', 1410, 0.29, 'Med', ['Sci'],
     {'Sci': 'Sciences'}, 'CA', 78000),
    ('Fordham University', 1350, 0.46, 'Med', ['Biz', 'Econ'],
     {'Biz': 'Gabelli', 'Econ': 'Economics'}, 'NY', 78000),
    ('GWU', 1380, 0.49, 'Med', ['Biz', 'Econ'],
     {'Biz': 'GW Business', 'Econ': 'Economics'}, 'DC', 78000),
    ('Syracuse University', 1310, 0.51, 'High', ['Biz', 'Eng', 'CS'],
     {'Biz': 'Whitman', 'Eng': 'Engineering', 'CS': 'iSchool'}, 'NY', 72000),
    ('University of Miami', 1370, 0.19, 'Med', ['Biz', 'Bio'],
     {'Biz': 'Miami Herbert', 'Bio': 'Miller Medicine'}, 'FL', 74000),
    ('SMU', 1380, 0.53, 'Med', ['Biz', 'CS'],
     {'Biz': 'Cox', 'CS': 'Lyle'}, 'TX', 76000),
    ('Stony Brook University', 1380, 0.49, 'High', ['CS', 'Sci', 'Eng'],
     {'CS': 'CS', 'Sci': 'A&S', 'Eng': 'Engineering'}, 'NY', 48000),
    ('Binghamton University', 1380, 0.42, 'Med', ['Biz', 'CS', 'Eng'],
     {'Biz': 'SOM', 'CS': 'Watson', 'Eng': 'Watson'}, 'NY', 46000),
    ('University of Denver', 1290, 0.78, 'Med', ['Biz'],
     {'Biz': 'Daniels'}, 'CO', 70000),
    ('Macalester College', 1400, 0.28, 'High', ['Econ'],
     {'Econ': 'Economics'}, 'MN', 72000),
    ('Lafayette College', 1380, 0.31, 'Med', ['Eng'],
     {'Eng': 'Engineering'}, 'PA', 74000),
    ('Bucknell University', 1360, 0.31, 'Med', ['Eng', 'Biz'],
     {'Eng': 'Engineering', 'Biz': 'Freeman'}, 'PA', 74000),
    ('Indiana University Bloomington', 1280, 0.8, 'High', ['Biz', 'CS'],
     {'Biz': 'Kelley', 'CS': 'Luddy'}, 'IN', 52000),
    ('Michigan State University', 1250, 0.83, 'Med', ['Biz', 'Eng', 'CS'],
     {'Biz': 'Broad', 'Eng': 'Engineering', 'CS': 'CSE'}, 'MI', 56000),
    ('University of Delaware', 1270, 0.7, 'Med', ['Eng', 'Biz'],
     {'Eng': 'Engineering', 'Biz': 'Lerner'}, 'DE', 52000),
    ('Drexel University', 1300, 0.76, 'High', ['CS', 'Eng', 'Biz'],
     {'CS': 'CCI', 'Eng': 'Engineering', 'Biz': 'LeBow'}, 'PA', 72000),
    ('Trinity College CT', 1360, 0.3, 'Med', ['Econ'],
     {'Econ': 'Economics'}, 'CT', 74000),
    ('Bryn Mawr College', 1390, 0.3, 'Med', ['Sci'],
     {'Sci': 'Sciences'}, 'PA', 72000),
    ('Smith College', 1390, 0.27, 'Med', ['Eng', 'Sci'],
     {'Eng': 'Engineering', 'Sci': 'Sciences'}, 'MA', 74000),
    ('Union College NY', 1350, 0.38, 'Med', ['Eng'],
     {'Eng': 'Engineering'}, 'NY', 74000),
    ('University at Buffalo SUNY', 1280, 0.68, 'High', ['Eng', 'CS', 'Biz'],
     {'Eng': 'Engineering', 'CS': 'CSE', 'Biz': 'School of Management'}, 'NY', 46000),
    ('Clemson University', 1320, 0.49, 'Low', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'SC', 52000),
    ('Auburn University', 1250, 0.75, 'Low', ['Eng'],
     {'Eng': 'Ginn Engineering'}, 'AL', 48000),
    ('Baylor University', 1280, 0.68, 'Med', ['Biz', 'Eng'],
     {'Biz': 'Hankamer', 'Eng': 'Engineering'}, 'TX', 66000),
    ('Connecticut College', 1360, 0.33, 'Med', ['Econ'],
     {'Econ': 'Economics'}, 'CT', 74000),
    ('Mount Holyoke College', 1370, 0.4, 'Med', ['Sci'],
     {'Sci': 'Sciences'}, 'MA', 72000),
    ('Marquette University', 1260, 0.83, 'Med', ['Biz', 'Eng'],
     {'Biz': 'Business', 'Eng': 'Engineering'}, 'WI', 60000),
    ('University of Iowa', 1230, 0.86, 'High', ['Bio', 'Biz'],
     {'Bio': 'Carver', 'Biz': 'Tippie'}, 'IA', 48000),
    ('University of Utah', 1260, 0.89, 'Med', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'Kahlert'}, 'UT', 48000),
    ('UT Dallas', 1320, 0.8, 'High', ['CS', 'Biz', 'Eng'],
     {'CS': 'Erik Jonsson', 'Biz': 'Jindal', 'Eng': 'Engineering'}, 'TX', 48000),
    ('Stevens Institute of Technology', 1400, 0.46, 'High', ['Eng', 'CS', 'Biz'],
     {'Eng': 'Schaefer', 'CS': 'CS', 'Biz': 'Business'}, 'NJ', 76000),
    ('Colorado School of Mines', 1390, 0.54, 'Med', ['Eng', 'Sci', 'CS'],
     {'Eng': 'Engineering', 'Sci': 'Applied Science', 'CS': 'CS'}, 'CO', 58000),
    ('RIT', 1310, 0.67, 'High', ['CS', 'Eng'],
     {'CS': 'Golisano', 'Eng': 'Kate Gleason'}, 'NY', 66000),
    ('American University', 1330, 0.41, 'Med', ['Biz', 'Econ'],
     {'Biz': 'Kogod', 'Econ': 'Economics'}, 'DC', 70000),
    ('SDSU', 1230, 0.39, 'Med', ['Biz', 'Eng'],
     {'Biz': 'Fowler', 'Eng': 'Engineering'}, 'CA', 40000),
    ('Florida State University', 1300, 0.25, 'Low', ['Biz'],
     {'Biz': 'Business'}, 'FL', 42000),
    ('NJIT', 1300, 0.68, 'High', ['CS', 'Eng'],
     {'CS': 'Ying Wu', 'Eng': 'NCE'}, 'NJ', 50000),
    ('Loyola University Chicago', 1290, 0.73, 'Med', ['Biz'],
     {'Biz': 'Quinlan'}, 'IL', 62000),
    ('Kettering University', 1300, 0.72, 'High', ['Eng'],
     {'Eng': 'Engineering'}, 'MI', 60000),
    ('University of South Carolina', 1280, 0.68, 'Med', ['Biz'],
     {'Biz': 'Darla Moore'}, 'SC', 52000),
    ('University of Tennessee', 1270, 0.74, 'Med', ['Eng', 'Biz'],
     {'Eng': 'Tickle Engineering', 'Biz': 'Haslam'}, 'TN', 48000),
    ('University of Nebraska Lincoln', 1230, 0.78, 'Med', ['Eng'],
     {'Eng': 'Engineering'}, 'NE', 44000),
    ('Clarkson University', 1280, 0.72, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'NY', 62000),
    ('ASU', 1260, 0.88, 'High', ['Biz', 'Eng', 'CS'],
     {'Biz': 'W.P. Carey', 'Eng': 'Fulton', 'CS': 'SCAI'}, 'AZ', 50000),
    ('University of Arizona', 1230, 0.87, 'High', ['Biz', 'Eng', 'Sci'],
     {'Biz': 'Eller', 'Eng': 'Engineering', 'Sci': 'Optical Sciences'}, 'AZ', 48000),
    ('UC Riverside', 1200, 0.69, 'High', ['Eng', 'CS'],
     {'Eng': 'Bourns', 'CS': 'CS'}, 'CA', 66000),
    ('UC Santa Cruz', 1280, 0.47, 'Med', ['CS', 'Sci'],
     {'CS': 'Baskin', 'Sci': 'Sciences'}, 'CA', 66000),
    ('Illinois Tech (IIT Chicago)', 1310, 0.56, 'High', ['Eng', 'CS'],
     {'Eng': 'Armour', 'CS': 'CS'}, 'IL', 62000),
    ('University of Oregon', 1230, 0.83, 'Med', ['Biz'],
     {'Biz': 'Lundquist'}, 'OR', 52000),
    ('Colorado State University', 1230, 0.84, 'Med', ['Eng', 'Sci'],
     {'Eng': 'Walter Scott', 'Sci': 'Sciences'}, 'CO', 48000),
    ('University of Vermont', 1280, 0.67, 'Med', ['Bio', 'Sci'],
     {'Bio': 'Larner Medicine', 'Sci': 'Sciences'}, 'VT', 58000),
    ('Creighton University', 1270, 0.7, 'Med', ['Bio', 'Biz'],
     {'Bio': 'Health Sciences', 'Biz': 'Heider'}, 'NE', 58000),
    ('University of San Francisco', 1250, 0.64, 'High', ['Biz'],
     {'Biz': 'School of Management'}, 'CA', 68000),
    ('Temple University', 1250, 0.79, 'High', ['Biz', 'Eng'],
     {'Biz': 'Fox', 'Eng': 'Engineering'}, 'PA', 50000),
    ('Oregon State University', 1210, 0.83, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'EECS'}, 'OR', 48000),
    ('University of South Florida', 1260, 0.44, 'Med', ['Eng', 'Bio'],
     {'Eng': 'Engineering', 'Bio': 'Morsani Medicine'}, 'FL', 38000),
    ('UCF', 1280, 0.41, 'Med', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'FL', 38000),
    ('University of Houston', 1230, 0.66, 'High', ['Biz', 'Eng'],
     {'Biz': 'Bauer', 'Eng': 'Cullen'}, 'TX', 42000),
    ('MSOE', 1320, 0.66, 'High', ['Eng'],
     {'Eng': 'Engineering'}, 'WI', 58000),
    ('New Mexico Tech', 1280, 0.46, 'High', ['Eng', 'Sci'],
     {'Eng': 'Engineering', 'Sci': 'Sciences'}, 'NM', 36000),
    ('University of Massachusetts Dartmouth', 1160, 0.82, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'MA', 44000),
    ('San Jose State University', 1200, 0.75, 'High', ['CS', 'Eng'],
     {'CS': 'CS', 'Eng': 'Davidson'}, 'CA', 36000),
    ('University of Oklahoma', 1220, 0.72, 'Med', ['Biz', 'Eng'],
     {'Biz': 'Price', 'Eng': 'Gallogly'}, 'OK', 42000),
    ('University of Central Missouri', 1100, 0.9, 'High', ['CS', 'Biz'],
     {'CS': 'CS', 'Biz': 'Harmon'}, 'MO', 26000),
    ('University of Kansas', 1180, 0.88, 'Med', ['Eng', 'Biz'],
     {'Eng': 'Engineering', 'Biz': 'Business'}, 'KS', 44000),
    ('University of Kentucky', 1200, 0.94, 'Med', ['Eng', 'Biz'],
     {'Eng': 'Engineering', 'Biz': 'Gatton'}, 'KY', 46000),
    ('LSU', 1190, 0.75, 'Med', ['Biz', 'Eng'],
     {'Biz': 'Ourso', 'Eng': 'Engineering'}, 'LA', 44000),
    ('Washington State University', 1130, 0.83, 'Med', ['Eng', 'CS'],
     {'Eng': 'Voiland', 'CS': 'CS'}, 'WA', 44000),
    ('Iowa State University', 1180, 0.9, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'IA', 40000),
    ('University of Missouri', 1210, 0.79, 'Med', ['Biz'],
     {'Biz': 'Trulaske'}, 'MO', 42000),
    ('University of Arkansas', 1190, 0.79, 'Med', ['Biz', 'Eng'],
     {'Biz': 'Walton', 'Eng': 'Engineering'}, 'AR', 40000),
    ('University of Alabama', 1220, 0.8, 'Low', ['Eng', 'Biz'],
     {'Eng': 'Engineering', 'Biz': 'Culverhouse'}, 'AL', 48000),
    ('George Mason University', 1220, 0.9, 'High', ['CS', 'Eng', 'Biz'],
     {'CS': 'Engineering & Computing', 'Eng': 'Engineering', 'Biz': 'Business'}, 'VA', 48000),
    ('DePaul University', 1190, 0.7, 'Med', ['Biz', 'CS'],
     {'Biz': 'Driehaus', 'CS': 'CDM'}, 'IL', 56000),
    ('Seton Hall University', 1230, 0.75, 'Med', ['Biz'],
     {'Biz': 'Stillman'}, 'NJ', 58000),
    ('Hofstra University', 1250, 0.69, 'Med', ['Biz'],
     {'Biz': 'Zarb'}, 'NY', 62000),
    ('University of Cincinnati', 1240, 0.86, 'High', ['Eng', 'Biz', 'CS'],
     {'Eng': 'CEAS', 'Biz': 'Lindner', 'CS': 'CEAS'}, 'OH', 44000),
    ('UMBC', 1290, 0.63, 'High', ['CS', 'Eng'],
     {'CS': 'CSEE', 'Eng': 'Engineering'}, 'MD', 44000),
    ('UIC', 1150, 0.79, 'High', ['Eng', 'CS', 'Bio'],
     {'Eng': 'Engineering', 'CS': 'CS', 'Bio': 'Medicine'}, 'IL', 44000),
    ('Texas Tech University', 1190, 0.67, 'Med', ['Biz', 'Eng'],
     {'Biz': 'Rawls', 'Eng': 'Whitacre'}, 'TX', 38000),
    ('Oklahoma State University', 1150, 0.7, 'Med', ['Biz', 'Eng'],
     {'Biz': 'Spears', 'Eng': 'Engineering'}, 'OK', 38000),
    ('Kansas State University', 1170, 0.95, 'Med', ['Eng'],
     {'Eng': 'Engineering'}, 'KS', 38000),
    ('West Virginia University', 1120, 0.9, 'Med', ['Eng'],
     {'Eng': 'Statler'}, 'WV', 40000),
    ('University of Tulsa', 1280, 0.76, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'OK', 56000),
    ('Northern Arizona University', 1120, 0.8, 'High', ['Eng'],
     {'Eng': 'Engineering'}, 'AZ', 40000),
    ('FIU', 1200, 0.64, 'High', ['Biz', 'Eng', 'CS'],
     {'Biz': 'Business', 'Eng': 'Engineering', 'CS': 'SCIS'}, 'FL', 36000),
    ('Georgia State University', 1120, 0.61, 'High', ['Biz', 'CS'],
     {'Biz': 'Robinson', 'CS': 'CS'}, 'GA', 42000),
    ('UNLV', 1100, 0.85, 'High', ['Eng', 'Biz'],
     {'Eng': 'Howard Hughes', 'Biz': 'Lee'}, 'NV', 38000),
    ('Pace University', 1150, 0.83, 'High', ['Biz', 'CS'],
     {'Biz': 'Lubin', 'CS': 'Seidenberg'}, 'NY', 62000),
    ('Suffolk University', 1130, 0.87, 'High', ['Biz'],
     {'Biz': 'Sawyer'}, 'MA', 56000),
    ('UMass Boston', 1120, 0.79, 'High', ['CS', 'Eng'],
     {'CS': 'CS', 'Eng': 'Engineering'}, 'MA', 48000),
    ('UMass Lowell', 1240, 0.85, 'High', ['Eng', 'CS'],
     {'Eng': 'Francis', 'CS': 'CS'}, 'MA', 50000),
    ('CSULB', 1120, 0.4, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'CA', 34000),
    ('CSUF', 1110, 0.67, 'High', ['Biz', 'Eng'],
     {'Biz': 'Mihaylo', 'Eng': 'Engineering'}, 'CA', 34000),
    ('SFSU', 1060, 0.93, 'High', ['Biz', 'CS'],
     {'Biz': 'Lam Family', 'CS': 'CS'}, 'CA', 32000),
    ('Wichita State University', 1110, 0.93, 'High', ['Eng'],
     {'Eng': 'Engineering'}, 'KS', 30000),
    ('Wright State University', 1100, 0.96, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'OH', 32000),
    ('University of Texas at Arlington', 1170, 0.8, 'High', ['Eng', 'CS', 'Biz'],
     {'Eng': 'Engineering', 'CS': 'CSE', 'Biz': 'Business'}, 'TX', 38000),
    ('University of Texas at San Antonio', 1120, 0.82, 'High', ['CS', 'Biz'],
     {'CS': 'CS', 'Biz': 'Alvarez'}, 'TX', 36000),
    ('University of North Texas', 1140, 0.76, 'High', ['CS', 'Biz'],
     {'CS': 'CS', 'Biz': 'G. Brint Ryan'}, 'TX', 36000),
    ('University of Dayton', 1240, 0.75, 'High', ['Eng', 'Biz'],
     {'Eng': 'Engineering', 'Biz': 'Business'}, 'OH', 56000),
    ('Clark University', 1280, 0.62, 'High', ['Biz', 'Sci'],
     {'Biz': 'GSOM', 'Sci': 'Sciences'}, 'MA', 56000),
    ('Rochester Institute of Technology', 1310, 0.67, 'High', ['CS', 'Eng'],
     {'CS': 'Golisano', 'Eng': 'Kate Gleason'}, 'NY', 66000),
    ('University of Bridgeport', 1020, 0.75, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'CT', 44000),
    ('University of New Haven', 1160, 0.83, 'High', ['Eng', 'CS'],
     {'Eng': 'Tagliatela', 'CS': 'CS'}, 'CT', 56000),
    ('SUNY New Paltz', 1220, 0.47, 'Med', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'NY', 38000),
    ('University at Albany SUNY', 1190, 0.6, 'High', ['CS', 'Biz'],
     {'CS': 'CS', 'Biz': 'Business'}, 'NY', 42000),
    ('Missouri S&T', 1320, 0.8, 'High', ['Eng', 'CS', 'Sci'],
     {'Eng': 'Engineering', 'CS': 'CS', 'Sci': 'Sciences'}, 'MO', 38000),
    ('South Dakota State University', 1110, 0.88, 'High', ['Eng'],
     {'Eng': 'Engineering'}, 'SD', 26000),
    ('North Dakota State University', 1130, 0.92, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'ND', 26000),
    ('University of Mississippi', 1160, 0.87, 'Med', ['Biz'],
     {'Biz': 'Business'}, 'MS', 38000),
    ('Mississippi State University', 1150, 0.69, 'Med', ['Eng'],
     {'Eng': 'Bagley Engineering'}, 'MS', 36000),
    ('University of New Hampshire', 1230, 0.77, 'Med', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'NH', 52000),
    ('Michigan Technological University', 1280, 0.81, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'MI', 48000),
    ('University of Idaho', 1110, 0.77, 'High', ['Eng'],
     {'Eng': 'Engineering'}, 'ID', 36000),
    ('Portland State University', 1120, 0.92, 'High', ['CS', 'Eng'],
     {'CS': 'CS', 'Eng': 'Engineering'}, 'OR', 40000),
    ('Wayne State University', 1130, 0.78, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'MI', 42000),
    ('University of Wisconsin Milwaukee', 1130, 0.85, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'WI', 38000),
    ('Old Dominion University', 1120, 0.84, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'VA', 38000),
    ('Lamar University', 1060, 0.84, 'High', ['Eng'],
     {'Eng': 'Engineering'}, 'TX', 30000),
    ('New York Institute of Technology', 1150, 0.7, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'NY', 56000),
    ('Embry-Riddle Aeronautical', 1280, 0.62, 'Med', ['Eng'],
     {'Eng': 'Engineering'}, 'FL', 56000),
    ('University of Akron', 1100, 0.96, 'High', ['Eng'],
     {'Eng': 'Engineering'}, 'OH', 34000),
    ('University of Louisville', 1180, 0.71, 'Med', ['Eng', 'Biz'],
     {'Eng': 'Speed Engineering', 'Biz': 'Business'}, 'KY', 44000),
    ('Rowan University', 1230, 0.81, 'High', ['Eng', 'CS'],
     {'Eng': 'Henry M. Rowan', 'CS': 'CS'}, 'NJ', 44000),
    ('University of Memphis', 1110, 0.9, 'High', ['Eng', 'CS'],
     {'Eng': 'Herff Engineering', 'CS': 'CS'}, 'TN', 36000),
    ('Wentworth Institute of Technology', 1240, 0.83, 'High', ['Eng', 'CS'],
     {'Eng': 'Engineering', 'CS': 'CS'}, 'MA', 56000),
]
